### ISSUE TITLE
The action triggers on every github comment

### ISSUE THREAD

**Issue by Therzok** [cirrus-actions/rebase#22]
The action is pretty wasteful, as in, it checks out the repository and only _then_ checks for the comment containing /rebase.

It would be better if it did the comment check first.

**Comment by fkorotkov** [comment]
Seems Actions now allow to do this:

```yaml
jobs:
  rebase:
    name: Rebase
    if: contains(github.event.comment.body, '/rebase')
```

Updated README
