### ISSUE TITLE
Suggestion: Trigger rebase using labels

### ISSUE THREAD

**Issue by matthijskooijman** [cirrus-actions/rebase#53]
To reduce the noise on a PR from a /rebase comment, it might be interesting to let the rebase be triggered by a label. E.g.:
 - You add a "needs-rebase" label to the PR
 - This triggers the rebase action
 - After rebasing, the label is removed by the action

I suspect that this might not actually need any changes to the action itself, just a different workflow configuration (this would require a way to remove a label, but it seems [there is an action for that](https://github.com/marketplace/actions/add-remove-label), or it could be done using [github-script](https://github.com/marketplace/actions/add-remove-label)).

Anyone tried this already?

**Comment by fkorotkov** [comment]
I think in theory this should work:

```YAML
on: 
  issue:
    types: [labeled]
name: Automatic Rebase
jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && github.event.label == 'needs_rebase'
    # the rest is the same
```
