### ISSUE TITLE
action is skipped, why?

### ISSUE THREAD

**Issue by cenit** [cirrus-actions/rebase#81]
as per title, can anyone please help me understand why action is skipped here?
I have never seen it working correctly on this repo

https://github.com/AlexeyAB/darknet/actions/runs/956515006

link to comment that triggered the skipped run: https://github.com/AlexeyAB/darknet/pull/792#issuecomment-864871265

this is the yml in the repository. Note that I am *not* interested in CI automatically triggering afterwards, just rebasing to work

```
name: Automatic Rebase
on:
  issue_comment:
    types: [created]
jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase') && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'CONTRIBUTOR')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
