### ISSUE TITLE
Checkout repo in a custom path

### ISSUE THREAD

**Issue by antho-girard** [cirrus-actions/rebase#82]
Hi,

The `actions/checkout` action allows specifying a relative path.

But, by doing so the rebase fails and we get this error : `fatal: not a git repository (or any parent up to mount point /github)`

Is there a workaround? (I tried to add a step `cd some/custom/path` before rebasing but I got the same error)

Here is the workflow file : 

```yml
name: Automatic Rebase
on:
  issue_comment:
    types: [created]
jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          path: some/custom/path
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Thanks!

**Comment by fkorotkov** [comment]
Will [changing working directory for the whole action](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_iddefaultsrun) work for your use case?

```yaml
jobs:
  phpunit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
```
