### ISSUE TITLE
Minimum level of permissions

### ISSUE THREAD

**Issue by PastaPastaPasta** [cirrus-actions/rebase#84]
I'm attempting to utilize this action, while minimizing the scope of it's permissions. Currently the action file has
```
permissions:
  contents: read
  pull-requests: write
  issues: read
  # Enforce other not needed permissions are off
  actions: none
  checks: none
  deployments: none
  packages: none
  repository-projects: none
  security-events: none
  statuses: none
```
However, this doesn't work the action says `This check was skipped`

What are the minimum required permissions for this to work?
