### ISSUE TITLE
Rebase fails on forks

### ISSUE THREAD

**Issue by NotMyFault** [cirrus-actions/rebase#88]
Heyo, 

I have the following rebase configuration
```yaml
name: Rebase Pull Request
on:
  issue_comment:
    types: [created]

jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase') && github.event.comment.author_association == 'MEMBER'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.REBASE_TOKEN }}
          fetch-depth: 0
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.5
        env:
          GITHUB_TOKEN: ${{ secrets.REBASE_TOKEN }}
```
Yet "GitHub doesn't think that the PR is rebaseable!" when I or other organization members attempt to rebase PRs, which are submit from forks.
Did I configure something wrong, that it doesn't work on forks?
The action failure in question can be obtained here: https://github.com/IntellectualSites/PlotSquared/runs/4839797347?check_suite_focus=true
My comment, as an organization member and administrator, here: https://github.com/IntellectualSites/PlotSquared/pull/3452#issuecomment-1014397059
